brew 'git'
brew 'rg'
brew 'gnupg'
brew 'nvim'
brew 'tmux'
cask 'ghostty'
cask 'claude-code'

# Markdown
brew 'marksman'

# Javascript
brew 'nvm'
brew 'typescript-language-server'
brew 'prettierd'

# Ruby
brew 'rbenv'
brew 'ruby-lsp'
brew 'rubyfmt'

# Go
brew 'go'
brew 'golangci-lint'
brew 'golangci-lint-langserver'
brew 'gopls'

# Lua
brew 'lua'
brew 'lua-language-server'

# Rust
brew 'rust'
brew 'rust-analyzer'

# C
brew 'llvm'
