local config_dir = vim.env.DOTFILES
local file = io.open(config_dir .. "/colorscheme/orlok.json", "r")
if file == nil then error("Could not load colorscheme") end
local content = file:read("*a")
file:close()
local colors = vim.json.decode(content)

if vim.g.colors_name then vim.cmd("hi clear") end
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "orlok"
vim.g.terminal_color_0 = colors.black
vim.g.terminal_color_1 = colors.red
vim.g.terminal_color_2 = colors.green
vim.g.terminal_color_3 = colors.yellow
vim.g.terminal_color_4 = colors.purple
vim.g.terminal_color_5 = colors.pink
vim.g.terminal_color_6 = colors.cyan
vim.g.terminal_color_7 = colors.white
vim.g.terminal_color_8 = colors.selection
vim.g.terminal_color_9 = colors.brightRed
vim.g.terminal_color_10 = colors.brightGreen
vim.g.terminal_color_11 = colors.brightYellow
vim.g.terminal_color_12 = colors.brightBlue
vim.g.terminal_color_13 = colors.brightMagenta
vim.g.terminal_color_14 = colors.brightCyan
vim.g.terminal_color_15 = colors.brightWhite
vim.g.terminal_color_background = colors.background
vim.g.terminal_color_foreground = colors.foreground

local groups = {
  Normal = { fg = colors.foreground, bg = colors.background },
  NormalFloat = { fg = colors.foreground, bg = colors.background },
  Comment = { fg = colors.comment, italic = true },
  Constant = { fg = colors.yellow },
  String = { fg = colors.yellow },
  Character = { fg = colors.green },
  Number = { fg = colors.orange },
  Boolean = { fg = colors.cyan },
  Float = { fg = colors.orange },
  FloatBorder = { fg = colors.white },
  Operator = { fg = colors.purple },
  Keyword = { fg = colors.cyan },
  Keywords = { fg = colors.cyan },
  Identifier = { fg = colors.cyan },
  Function = { fg = colors.yellow },
  Statement = { fg = colors.purple },
  Conditional = { fg = colors.pink },
  Repeat = { fg = colors.pink },
  Label = { fg = colors.cyan },
  Exception = { fg = colors.purple },
  PreProc = { fg = colors.yellow },
  Include = { fg = colors.purple },
  Define = { fg = colors.purple },
  Title = { fg = colors.cyan },
  Macro = { fg = colors.purple },
  PreCondit = { fg = colors.cyan },
  Type = { fg = colors.cyan },
  StorageClass = { fg = colors.pink },
  Structure = { fg = colors.yellow },
  TypeDef = { fg = colors.yellow },
  Special = { fg = colors.green, italic = true },
  SpecialComment = { fg = colors.comment, italic = true },
  Error = { fg = colors.brightRed },
  Todo = { fg = colors.purple, bold = true, italic = true },
  Underlined = { fg = colors.cyan, underline = true },
  Cursor = { reverse = true },
  CursorLineNr = { fg = colors.foreground, bold = true },
  SignColumn = { bg = colors.background },
  Conceal = { fg = colors.comment },
  CursorColumn = { bg = colors.black },
  CursorLine = { bg = colors.selection },
  ColorColumn = { bg = colors.selection },
  StatusLine = { fg = colors.white, bg = colors.selection },
  StatusLineNC = { fg = colors.comment },
  StatusLineTerm = { fg = colors.white, bg = colors.black },
  StatusLineTermNC = { fg = colors.comment },
  Directory = { fg = colors.cyan },
  DiffAdd = { fg = colors.background, bg = colors.green },
  DiffChange = { fg = colors.orange },
  DiffDelete = { fg = colors.red },
  DiffText = { fg = colors.comment },
  ErrorMsg = { fg = colors.brightRed },
  VertSplit = { fg = colors.black },
  WinSeparator = { fg = colors.black },
  Folded = { fg = colors.comment },
  FoldColumn = {},
  Search = { fg = colors.black, bg = colors.orange },
  IncSearch = { fg = colors.orange, bg = colors.comment },
  LineNr = { fg = colors.comment },
  MatchParen = { fg = colors.foreground, underline = true },
  NonText = { fg = colors.nontext },
  Pmenu = { fg = colors.white, bg = colors.menu },
  PmenuSel = { fg = colors.white, bg = colors.selection },
  PmenuSbar = { bg = colors.background },
  PmenuThumb = { bg = colors.selection },
  Question = { fg = colors.purple },
  QuickFixLine = { fg = colors.black, bg = colors.yellow },
  SpecialKey = { fg = colors.nontext },
  SpellBad = { fg = colors.brightRed, underline = true },
  SpellCap = { fg = colors.yellow },
  SpellLocal = { fg = colors.yellow },
  SpellRare = { fg = colors.yellow },
  TabLine = { fg = colors.comment },
  TabLineSel = { fg = colors.white },
  TabLineFill = { bg = colors.background },
  Terminal = { fg = colors.white, bg = colors.black },
  Visual = { bg = colors.visual },
  VisualNOS = { fg = colors.visual },
  WarningMsg = { fg = colors.yellow },
  WildMenu = { fg = colors.black, bg = colors.white },
  EndOfBuffer = { fg = colors.background },

  -- TreeSitter
  ["@error"] = { fg = colors.brightRed },
  ["@punctuation.delimiter"] = { fg = colors.foreground },
  ["@punctuation.bracket"] = { fg = colors.foreground },
  ["@markup.list"] = { fg = colors.cyan },
  ["@constant"] = { fg = colors.purple },
  ["@constant.builtin"] = { fg = colors.purple },
  ["@markup.link.label.symbol"] = { fg = colors.purple },
  ["@constant.macro"] = { fg = colors.cyan },
  ["@string.regexp"] = { fg = colors.red },
  ["@string"] = { fg = colors.yellow },
  ["@string.escape"] = { fg = colors.cyan },
  ["@string.special.symbol"] = { fg = colors.purple },
  ["@character"] = { fg = colors.green },
  ["@number"] = { fg = colors.purple },
  ["@boolean"] = { fg = colors.purple },
  ["@number.float"] = { fg = colors.green },
  ["@annotation"] = { fg = colors.yellow },
  ["@attribute"] = { fg = colors.cyan },
  ["@module"] = { fg = colors.orange },
  ["@function.builtin"] = { fg = colors.cyan },
  ["@function"] = { fg = colors.green },
  ["@function.macro"] = { fg = colors.green },
  ["@variable.parameter"] = { fg = colors.orange },
  ["@variable.parameter.reference"] = { fg = colors.orange },
  ["@function.method"] = { fg = colors.green },
  ["@variable.member"] = { fg = colors.orange },
  ["@property"] = { fg = colors.purple },
  ["@constructor"] = { fg = colors.cyan },
  ["@keyword.conditional"] = { fg = colors.pink },
  ["@keyword.repeat"] = { fg = colors.pink },
  ["@label"] = { fg = colors.cyan },
  ["@keyword"] = { fg = colors.pink },
  ["@keyword.function"] = { fg = colors.cyan },
  ["@keyword.function.ruby"] = { fg = colors.pink },
  ["@keyword.operator"] = { fg = colors.pink },
  ["@operator"] = { fg = colors.pink },
  ["@keyword.exception"] = { fg = colors.purple },
  ["@type"] = { fg = colors.brightCyan },
  ["@type.builtin"] = { fg = colors.cyan, italic = true },
  ["@type.qualifier"] = { fg = colors.pink },
  ["@structure"] = { fg = colors.purple },
  ["@keyword.include"] = { fg = colors.pink },
  ["@variable"] = { fg = colors.foreground },
  ["@variable.builtin"] = { fg = colors.purple },
  ["@markup"] = { fg = colors.orange },
  ["@markup.strong"] = { fg = colors.orange, bold = true }, -- bold
  ["@markup.emphasis"] = { fg = colors.yellow, italic = true }, -- italic
  ["@markup.underline"] = { fg = colors.orange },
  ["@markup.heading"] = { fg = colors.pink, bold = true }, -- title
  ["@markup.raw"] = { fg = colors.yellow }, -- inline code
  ["@markup.link.url"] = { fg = colors.yellow, italic = true }, -- urls
  ["@markup.link"] = { fg = colors.orange, bold = true },
  ["@tag"] = { fg = colors.cyan },
  ["@tag.attribute"] = { fg = colors.green },
  ["@tag.delimiter"] = { fg = colors.cyan },

  -- Semantic
  ["@class"] = { fg = colors.cyan },
  ["@struct"] = { fg = colors.cyan },
  ["@enum"] = { fg = colors.cyan },
  ["@enumMember"] = { fg = colors.purple },
  ["@event"] = { fg = colors.cyan },
  ["@interface"] = { fg = colors.cyan },
  ["@modifier"] = { fg = colors.cyan },
  ["@regexp"] = { fg = colors.yellow },
  ["@typeParameter"] = { fg = colors.cyan },
  ["@decorator"] = { fg = colors.cyan },

  -- LSP Semantic (0.9+)
  ["@lsp.type.class"] = { fg = colors.cyan },
  ["@lsp.type.enum"] = { fg = colors.cyan },
  ["@lsp.type.decorator"] = { fg = colors.green },
  ["@lsp.type.enumMember"] = { fg = colors.purple },
  ["@lsp.type.function"] = { fg = colors.green },
  ["@lsp.type.interface"] = { fg = colors.cyan },
  ["@lsp.type.macro"] = { fg = colors.cyan },
  ["@lsp.type.method"] = { fg = colors.green },
  ["@lsp.type.namespace"] = { fg = colors.orange },
  ["@lsp.type.parameter"] = { fg = colors.orange },
  ["@lsp.type.property"] = { fg = colors.purple },
  ["@lsp.type.struct"] = { fg = colors.cyan },
  ["@lsp.type.type"] = { fg = colors.brightCyan },
  ["@lsp.type.variable"] = { fg = colors.foreground },

  -- HTML
  htmlArg = { fg = colors.green },
  htmlBold = { fg = colors.yellow, bold = true },
  htmlEndTag = { fg = colors.cyan },
  htmlH1 = { fg = colors.pink },
  htmlH2 = { fg = colors.pink },
  htmlH3 = { fg = colors.pink },
  htmlH4 = { fg = colors.pink },
  htmlH5 = { fg = colors.pink },
  htmlH6 = { fg = colors.pink },
  htmlItalic = { fg = colors.purple, italic = true },
  htmlLink = { fg = colors.purple, underline = true },
  htmlSpecialChar = { fg = colors.yellow },
  htmlSpecialTagName = { fg = colors.cyan },
  htmlTag = { fg = colors.cyan },
  htmlTagN = { fg = colors.cyan },
  htmlTagName = { fg = colors.cyan },
  htmlTitle = { fg = colors.white },

  -- Markdown
  markdownBlockquote = { fg = colors.yellow, italic = true },
  markdownBold = { fg = colors.orange, bold = true },
  markdownCode = { fg = colors.green },
  markdownCodeBlock = { fg = colors.orange },
  markdownCodeDelimiter = { fg = colors.red },
  markdownH2 = { link = "rainbow2" },
  markdownH1 = { link = "rainbow1" },
  markdownH3 = { link = "rainbow3" },
  markdownH4 = { link = "rainbow4" },
  markdownH5 = { link = "rainbow5" },
  markdownH6 = { link = "rainbow6" },
  markdownHeadingDelimiter = { fg = colors.red },
  markdownHeadingRule = { fg = colors.comment },
  markdownId = { fg = colors.purple },
  markdownIdDeclaration = { fg = colors.cyan },
  markdownIdDelimiter = { fg = colors.purple },
  markdownItalic = { fg = colors.yellow, italic = true },
  markdownLinkDelimiter = { fg = colors.purple },
  markdownLinkText = { fg = colors.pink },
  markdownListMarker = { fg = colors.cyan },
  markdownOrderedListMarker = { fg = colors.red },
  markdownRule = { fg = colors.comment },
  ["@markup.heading.1.markdown"] = { link = "rainbowcol1" },
  ["@markup.heading.2.markdown"] = { link = "rainbowcol2" },
  ["@markup.heading.3.markdown"] = { link = "rainbowcol3" },
  ["@markup.heading.4.markdown"] = { link = "rainbowcol4" },
  ["@markup.heading.5.markdown"] = { link = "rainbowcol5" },
  ["@markup.heading.6.markdown"] = { link = "rainbowcol6" },

  --  Diff
  diffAdded = { fg = colors.green },
  diffRemoved = { fg = colors.red },
  diffFileId = { fg = colors.yellow, bold = true, reverse = true },
  diffFile = { fg = colors.nontext },
  diffNewFile = { fg = colors.green },
  diffOldFile = { fg = colors.red },

  debugPc = { bg = colors.menu },
  debugBreakpoint = { fg = colors.red, reverse = true },

  -- Telescope
  TelescopePromptBorder = { fg = colors.comment },
  TelescopeResultsBorder = { fg = colors.comment },
  TelescopePreviewBorder = { fg = colors.comment },
  TelescopeSelection = { fg = colors.white, bg = colors.selection },
  TelescopeMultiSelection = { fg = colors.purple, bg = colors.selection },
  TelescopeNormal = { fg = colors.foreground, bg = colors.background },
  TelescopeMatching = { fg = colors.green },
  TelescopePromptPrefix = { fg = colors.purple },
  TelescopeResultsDiffDelete = { fg = colors.red },
  TelescopeResultsDiffChange = { fg = colors.cyan },
  TelescopeResultsDiffAdd = { fg = colors.green },

  -- LSP
  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInfo = { fg = colors.cyan },
  DiagnosticHint = { fg = colors.cyan },
  DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cyan },
  DiagnosticUnderlineHint = { undercurl = true, sp = colors.cyan },
  DiagnosticSignError = { fg = colors.red },
  DiagnosticSignWarn = { fg = colors.yellow },
  DiagnosticSignInfo = { fg = colors.cyan },
  DiagnosticSignHint = { fg = colors.cyan },
  DiagnosticFloatingError = { fg = colors.red },
  DiagnosticFloatingWarn = { fg = colors.yellow },
  DiagnosticFloatingInfo = { fg = colors.cyan },
  DiagnosticFloatingHint = { fg = colors.cyan },
  DiagnosticVirtualTextError = { fg = colors.red },
  DiagnosticVirtualTextWarn = { fg = colors.yellow },
  DiagnosticVirtualTextInfo = { fg = colors.cyan },
  DiagnosticVirtualTextHint = { fg = colors.cyan },

  LspDiagnosticsDefaultError = { fg = colors.red },
  LspDiagnosticsDefaultWarning = { fg = colors.yellow },
  LspDiagnosticsDefaultInformation = { fg = colors.cyan },
  LspDiagnosticsDefaultHint = { fg = colors.cyan },
  LspDiagnosticsUnderlineError = { fg = colors.red, undercurl = true },
  LspDiagnosticsUnderlineWarning = { fg = colors.yellow, undercurl = true },
  LspDiagnosticsUnderlineInformation = { fg = colors.cyan, undercurl = true },
  LspDiagnosticsUnderlineHint = { fg = colors.cyan, undercurl = true },
  LspReferenceText = { fg = colors.orange },
  LspReferenceRead = { fg = colors.orange },
  LspReferenceWrite = { fg = colors.orange },
  LspCodeLens = { fg = colors.cyan },
  LspInlayHint = { fg = colors.gray, bg = colors.backgroundLight },

  -- statusline
  SLNormal = { fg = colors.background, bg = colors.cyan },
  SLInsert = { fg = colors.foreground, bg = colors.green },
  SLVisual = { fg = colors.foreground, bg = colors.red },
  SLSelect = { fg = colors.foreground, bg = colors.yellow },
  SLReplace = { fg = colors.foreground, bg = colors.yellow },
  SLCommand = { fg = colors.foreground, bg = colors.orange },
  SLConfirm = { fg = colors.foreground, bg = colors.purple },
  SLTerminal = { fg = colors.foreground, bg = colors.purple },
  User1 = { fg = colors.foreground, bg = colors.background },
}

for group, setting in pairs(groups) do
  vim.api.nvim_set_hl(0, group, setting)
end
