source ~/.vim/config/options.vim    " set default options
source ~/.vim/config/keyboard.vim   " hotkeys
source ~/.vim/config/ale.vim        " code linting
source ~/.vim/config/gitgutter.vim  " style for the gitgutters
source ~/.vim/config/netrw.vim      " make netrw less ugly
source ~/.vim/config/autocmd.vim    " auto run scripts
source ~/.vim/config/disabled.vim   " hotkeys that I don't want
source ~/.vim/config/search.vim     " faster search
source ~/.vim/config/statusline.vim " custom command line
source ~/.vim/config/color.vim      " needs to be last
