source ~/.vim/config/options.vim    " set default options
source ~/.vim/config/keyboard.vim
source ~/.vim/config/ale.vim
source ~/.vim/config/gitgutter.vim
source ~/.vim/config/netrw.vim
source ~/.vim/config/autocmd.vim
source ~/.vim/config/disabled.vim
source ~/.vim/config/search.vim
source ~/.vim/config/statusline.vim " custom command line
source ~/.vim/config/color.vim      " needs to be last
