# cleanup HOME files
export XDG_CONFIG_HOME=$HOME/.config
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
export LESSHISTFILE=~/.config/less/history
export HISTFILE=$HOME/.config/zsh/history

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dracula/dracula"
COMPLETION_WAITING_DOTS="true"
plugins=(git rust nvm)
[ -f $ZSH/oh-my-zsh.sh ] && source $ZSH/oh-my-zsh.sh

export VISUAL=nvim
export EDITOR=nvim
export GOPATH=~/workspace/go
export GOPRIVATE=gitlab.com/pockethealth

export PATH="" # reset so my path will work as expected without touching /etc/paths
export PATH=$PATH:/opt/homebrew/bin:/opt/homebrew/sbin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.rbenv/shims
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/usr/bin
export PATH=$PATH:/usr/sbin
export PATH=$PATH:/bin
export PATH=$PATH:/sbin

alias reload='source ~/.zshrc'
