local none = 'NONE'
local function hi(group, ctermfg, ctermbg, cterm)
 vim.api.nvim_set_hl(0, group, {ctermfg = ctermfg, ctermbg = ctermbg, cterm = cterm})
end

local function link(group, linked)
 vim.api.nvim_set_hl(0, group, { link = linked })
end

hi'clear'
hi('Normal', 188, 233)
hi('CursorLine', none, 234)
hi('CursorColumn', none, 234)
hi('MatchParen', 231, 60, {bold = true})
hi('TabLine', 16, 145)
hi('TabLineFill', 103)
hi('TabLineSel', 16, 255, {bold = true})
hi('Pmenu', 231, 240)
hi('PmenuSel', 232, 255)
hi('Visual', none, 237)
hi('Cursor', 233, 153)
hi('LineNr', 59, 233)
hi('CursorLineNr', 188)
hi('Comment', 244)
hi('Todo', 251, none, {bold = true})
hi('StatusLine', 16, 253)
hi('StatusLineNC', 231, 16)
hi('VertSplit', 243, 16)
hi('WildMenu', 217, 16)
hi('Folded', 145, 16)
hi('FoldColumn', 59, 234)
hi('SignColumn', 243, 236)
hi('ColorColumn', none, 16)
hi('Title', 71, none, {bold = true})
hi('Constant', 167)
hi('Special', 107)
hi('Delimiter', 66)
hi('String', 107)
hi('StringDelimiter', 58)
hi('Identifier', 183)
hi('Structure', 110)
hi('Function', 222)
hi('Statement', 103)
hi('PreProc', 110)
hi('Type', 215)
hi('NonText', 240, 233)
hi('SpecialKey', 238, 234)
hi('Search', 217, 16, {underline = true})
hi('Directory', 186)
hi('ErrorMsg', none, 88)
hi('Question', 71)
hi('SpellBad', none, 88, {underline = true})
hi('SpellCap', none, 20, {underline = true})
hi('SpellRare', none, 53, {underline = true})
hi('SpellLocal', none, 23, {underline = true})
hi('DiffAdd', 193, 22)
hi('DiffDelete', 16, 52)
hi('DiffChange', none, 24)
hi('DiffText', 110, 16, {reverse = true})
hi('StorageClass', 179)
hi('rubyClass', 30)
hi('rubyIdentifier', 183)
hi('rubyInstanceVariable', 183)
hi('rubySymbol', 104)
hi('rubyControl', 104)
hi('rubyRegexpDelimiter', 53)
hi('rubyRegexp', 162)
hi('rubyRegexpSpecial', 126)
hi('rubyPredefinedIdentifier', 168)
hi('DbgCurrent', 195, 25)
hi('DbgBreakPt', none, 52)
hi('IndentGuidesOdd', none, 234)
hi('IndentGuidesEven', none, 233)
hi('PreciseJumpTarget', 155, 22)
hi('StatusLineNC', 235)
hi('Folded', 236)
hi('DiffText', 81)
hi('DbgBreakPt', 53)
hi('IndentGuidesOdd', 235)
hi('IndentGuidesEven', 234)

link('Operator', 'Structure')
link('Conceal', 'Operator')
link('Error', 'ErrorMsg')
link('MoreMsg', 'Special')
link('diffRemoved', 'Constant')
link('diffAdded', 'String')
link('phpFunctions', 'Function')
link('phpSuperglobal', 'Identifier')
link('phpQuoteSingle', 'StringDelimiter')
link('phpQuoteDouble', 'StringDelimiter')
link('phpBoolean', 'Constant')
link('phpNull', 'Constant')
link('phpArrayPair', 'Operator')
link('phpOperator', 'Normal')
link('phpRelation', 'Normal')
link('phpVarSelector', 'Identifier')
link('pythonOperator', 'Statement')
link('rubySharpBang', 'Comment')
link('rubyConstant', 'Type')
link('rubyFunction', 'Function')
link('rubyGlobalVariable', 'rubyInstanceVariable')
link('rubyModule', 'rubyClass')
link('rubyString', 'String')
link('rubyStringDelimiter', 'StringDelimiter')
link('rubyInterpolationDelimiter', 'Identifier')
link('erlangAtom', 'rubySymbol')
link('erlangBIF', 'rubyPredefinedIdentifier')
link('erlangFunction', 'rubyPredefinedIdentifier')
link('erlangDirective', 'Statement')
link('erlangNode', 'Identifier')
link('elixirAtom', 'rubySymbol')
link('javaScriptValue', 'Constant')
link('javaScriptRegexpString', 'rubyRegexp')
link('javaScriptTemplateVar', 'StringDelim')
link('javaScriptTemplateDelim', 'Identifier')
link('javaScriptTemplateString', 'String')
link('coffeeRegExp', 'javaScriptRegexpString')
link('luaOperator', 'Conditional')
link('cFormat', 'Identifier')
link('cOperator', 'Constant')
link('objcClass', 'Type')
link('cocoaClass', 'objcClass')
link('objcSubclass', 'objcClass')
link('objcSuperclass', 'objcClass')
link('objcDirective', 'rubyClass')
link('objcStatement', 'Constant')
link('cocoaFunction', 'Function')
link('objcMethodName', 'Identifier')
link('objcMethodArg', 'Normal')
link('objcMessageName', 'Identifier')
link('vimOper', 'Normal')
link('htmlTag', 'Statement')
link('htmlEndTag', 'htmlTag')
link('htmlTagName', 'htmlTag')
link('xmlTag', 'Statement')
link('xmlEndTag', 'xmlTag')
link('xmlTagName', 'xmlTag')
link('xmlEqual', 'xmlTag')
link('xmlEntity', 'Special')
link('xmlEntityPunct', 'xmlEntity')
link('xmlDocTypeDecl', 'PreProc')
link('xmlDocTypeKeyword', 'PreProc')
link('xmlProcessingDelim', 'xmlAttrib')
link('TagListFileName', 'Directory')
