export DO_NOT_TRACK=1
export VISUAL=nvim
export EDITOR=nvim

source "$HOME/.config/zsh/xdg_setup.sh"
source "$HOME/.config/zsh/path_setup.sh"
source "$HOME/.config/zsh/alias.sh"
source "$ZSH/themes/dracula/dracula.zsh-theme"
