local config_dir = vim.env.DOTFILES
local file = io.open(config_dir .. "/colorscheme/dracula.json", "r")
if file == nil then error("Could not load colorscheme") end
local content = file:read("*a")
file:close()
local colorPalette = vim.json.decode(content)

local GROUPS = {
  Normal = { fg = colorPalette.foreground, bg = colorPalette.background },
  NormalFloat = { fg = colorPalette.foreground, bg = colorPalette.background },
  Comment = { fg = colorPalette.comment, italic = true },
  Constant = { fg = colorPalette.yellow },
  String = { fg = colorPalette.yellow },
  Character = { fg = colorPalette.green },
  Number = { fg = colorPalette.orange },
  Boolean = { fg = colorPalette.cyan },
  Float = { fg = colorPalette.orange },
  FloatBorder = { fg = colorPalette.white },
  Operator = { fg = colorPalette.purple },
  Keyword = { fg = colorPalette.cyan },
  Keywords = { fg = colorPalette.cyan },
  Identifier = { fg = colorPalette.cyan },
  Function = { fg = colorPalette.yellow },
  Statement = { fg = colorPalette.purple },
  Conditional = { fg = colorPalette.pink },
  Repeat = { fg = colorPalette.pink },
  Label = { fg = colorPalette.cyan },
  Exception = { fg = colorPalette.purple },
  PreProc = { fg = colorPalette.yellow },
  Include = { fg = colorPalette.purple },
  Define = { fg = colorPalette.purple },
  Title = { fg = colorPalette.cyan },
  Macro = { fg = colorPalette.purple },
  PreCondit = { fg = colorPalette.cyan },
  Type = { fg = colorPalette.cyan },
  StorageClass = { fg = colorPalette.pink },
  Structure = { fg = colorPalette.yellow },
  TypeDef = { fg = colorPalette.yellow },
  Special = { fg = colorPalette.green, italic = true },
  SpecialComment = { fg = colorPalette.comment, italic = true },
  Error = { fg = colorPalette.brightRed },
  Todo = { fg = colorPalette.purple, bold = true, italic = true },
  Underlined = { fg = colorPalette.cyan, underline = true },
  Cursor = { reverse = true },
  CursorLineNr = { fg = colorPalette.foreground, bold = true },
  SignColumn = { bg = colorPalette.background },
  Conceal = { fg = colorPalette.comment },
  CursorColumn = { bg = colorPalette.black },
  CursorLine = { bg = colorPalette.selection },
  ColorColumn = { bg = colorPalette.selection },
  StatusLine = { fg = colorPalette.white, bg = colorPalette.selection },
  StatusLineNC = { fg = colorPalette.comment },
  StatusLineTerm = { fg = colorPalette.white, bg = colorPalette.black },
  StatusLineTermNC = { fg = colorPalette.comment },
  Directory = { fg = colorPalette.cyan },
  DiffAdd = { fg = colorPalette.background, bg = colorPalette.green },
  DiffChange = { fg = colorPalette.orange },
  DiffDelete = { fg = colorPalette.red },
  DiffText = { fg = colorPalette.comment },
  ErrorMsg = { fg = colorPalette.brightRed },
  VertSplit = { fg = colorPalette.black },
  WinSeparator = { fg = colorPalette.black },
  Folded = { fg = colorPalette.comment },
  FoldColumn = {},
  Search = { fg = colorPalette.black, bg = colorPalette.orange },
  IncSearch = { fg = colorPalette.orange, bg = colorPalette.comment },
  LineNr = { fg = colorPalette.comment },
  MatchParen = { fg = colorPalette.foreground, underline = true },
  NonText = { fg = colorPalette.nontext },
  Pmenu = { fg = colorPalette.white, bg = colorPalette.menu },
  PmenuSel = { fg = colorPalette.white, bg = colorPalette.selection },
  PmenuSbar = { bg = colorPalette.background },
  PmenuThumb = { bg = colorPalette.selection },
  Question = { fg = colorPalette.purple },
  QuickFixLine = { fg = colorPalette.black, bg = colorPalette.yellow },
  SpecialKey = { fg = colorPalette.nontext },
  SpellBad = { fg = colorPalette.brightRed, underline = true },
  SpellCap = { fg = colorPalette.yellow },
  SpellLocal = { fg = colorPalette.yellow },
  SpellRare = { fg = colorPalette.yellow },
  TabLine = { fg = colorPalette.comment },
  TabLineSel = { fg = colorPalette.white },
  TabLineFill = { bg = colorPalette.background },
  Terminal = { fg = colorPalette.white, bg = colorPalette.black },
  Visual = { bg = colorPalette.visual },
  VisualNOS = { fg = colorPalette.visual },
  WarningMsg = { fg = colorPalette.yellow },
  WildMenu = { fg = colorPalette.black, bg = colorPalette.white },
  EndOfBuffer = { fg = colorPalette.background },

  -- TreeSitter
  ["@error"] = { fg = colorPalette.brightRed },
  ["@punctuation.delimiter"] = { fg = colorPalette.foreground },
  ["@punctuation.bracket"] = { fg = colorPalette.foreground },
  ["@markup.list"] = { fg = colorPalette.cyan },
  ["@constant"] = { fg = colorPalette.purple },
  ["@constant.builtin"] = { fg = colorPalette.purple },
  ["@markup.link.label.symbol"] = { fg = colorPalette.purple },
  ["@constant.macro"] = { fg = colorPalette.cyan },
  ["@string.regexp"] = { fg = colorPalette.red },
  ["@string"] = { fg = colorPalette.yellow },
  ["@string.escape"] = { fg = colorPalette.cyan },
  ["@string.special.symbol"] = { fg = colorPalette.purple },
  ["@character"] = { fg = colorPalette.green },
  ["@number"] = { fg = colorPalette.purple },
  ["@boolean"] = { fg = colorPalette.purple },
  ["@number.float"] = { fg = colorPalette.green },
  ["@annotation"] = { fg = colorPalette.yellow },
  ["@attribute"] = { fg = colorPalette.cyan },
  ["@module"] = { fg = colorPalette.orange },
  ["@function.builtin"] = { fg = colorPalette.cyan },
  ["@function"] = { fg = colorPalette.green },
  ["@function.macro"] = { fg = colorPalette.green },
  ["@variable.parameter"] = { fg = colorPalette.orange },
  ["@variable.parameter.reference"] = { fg = colorPalette.orange },
  ["@function.method"] = { fg = colorPalette.green },
  ["@variable.member"] = { fg = colorPalette.orange },
  ["@property"] = { fg = colorPalette.purple },
  ["@constructor"] = { fg = colorPalette.cyan },
  ["@keyword.conditional"] = { fg = colorPalette.pink },
  ["@keyword.repeat"] = { fg = colorPalette.pink },
  ["@label"] = { fg = colorPalette.cyan },
  ["@keyword"] = { fg = colorPalette.pink },
  ["@keyword.function"] = { fg = colorPalette.cyan },
  ["@keyword.function.ruby"] = { fg = colorPalette.pink },
  ["@keyword.operator"] = { fg = colorPalette.pink },
  ["@operator"] = { fg = colorPalette.pink },
  ["@keyword.exception"] = { fg = colorPalette.purple },
  ["@type"] = { fg = colorPalette.brightCyan },
  ["@type.builtin"] = { fg = colorPalette.cyan, italic = true },
  ["@type.qualifier"] = { fg = colorPalette.pink },
  ["@structure"] = { fg = colorPalette.purple },
  ["@keyword.include"] = { fg = colorPalette.pink },
  ["@variable"] = { fg = colorPalette.foreground },
  ["@variable.builtin"] = { fg = colorPalette.purple },
  ["@markup"] = { fg = colorPalette.orange },
  ["@markup.strong"] = { fg = colorPalette.orange, bold = true }, -- bold
  ["@markup.emphasis"] = { fg = colorPalette.yellow, italic = true }, -- italic
  ["@markup.underline"] = { fg = colorPalette.orange },
  ["@markup.heading"] = { fg = colorPalette.pink, bold = true }, -- title
  ["@markup.raw"] = { fg = colorPalette.yellow }, -- inline code
  ["@markup.link.url"] = { fg = colorPalette.yellow, italic = true }, -- urls
  ["@markup.link"] = { fg = colorPalette.orange, bold = true },
  ["@tag"] = { fg = colorPalette.cyan },
  ["@tag.attribute"] = { fg = colorPalette.green },
  ["@tag.delimiter"] = { fg = colorPalette.cyan },

  -- Semantic
  ["@class"] = { fg = colorPalette.cyan },
  ["@struct"] = { fg = colorPalette.cyan },
  ["@enum"] = { fg = colorPalette.cyan },
  ["@enumMember"] = { fg = colorPalette.purple },
  ["@event"] = { fg = colorPalette.cyan },
  ["@interface"] = { fg = colorPalette.cyan },
  ["@modifier"] = { fg = colorPalette.cyan },
  ["@regexp"] = { fg = colorPalette.yellow },
  ["@typeParameter"] = { fg = colorPalette.cyan },
  ["@decorator"] = { fg = colorPalette.cyan },

  -- LSP Semantic (0.9+)
  ["@lsp.type.class"] = { fg = colorPalette.cyan },
  ["@lsp.type.enum"] = { fg = colorPalette.cyan },
  ["@lsp.type.decorator"] = { fg = colorPalette.green },
  ["@lsp.type.enumMember"] = { fg = colorPalette.purple },
  ["@lsp.type.function"] = { fg = colorPalette.green },
  ["@lsp.type.interface"] = { fg = colorPalette.cyan },
  ["@lsp.type.macro"] = { fg = colorPalette.cyan },
  ["@lsp.type.method"] = { fg = colorPalette.green },
  ["@lsp.type.namespace"] = { fg = colorPalette.orange },
  ["@lsp.type.parameter"] = { fg = colorPalette.orange },
  ["@lsp.type.property"] = { fg = colorPalette.purple },
  ["@lsp.type.struct"] = { fg = colorPalette.cyan },
  ["@lsp.type.type"] = { fg = colorPalette.brightCyan },
  ["@lsp.type.variable"] = { fg = colorPalette.foreground },

  -- HTML
  htmlArg = { fg = colorPalette.green },
  htmlBold = { fg = colorPalette.yellow, bold = true },
  htmlEndTag = { fg = colorPalette.cyan },
  htmlH1 = { fg = colorPalette.pink },
  htmlH2 = { fg = colorPalette.pink },
  htmlH3 = { fg = colorPalette.pink },
  htmlH4 = { fg = colorPalette.pink },
  htmlH5 = { fg = colorPalette.pink },
  htmlH6 = { fg = colorPalette.pink },
  htmlItalic = { fg = colorPalette.purple, italic = true },
  htmlLink = { fg = colorPalette.purple, underline = true },
  htmlSpecialChar = { fg = colorPalette.yellow },
  htmlSpecialTagName = { fg = colorPalette.cyan },
  htmlTag = { fg = colorPalette.cyan },
  htmlTagN = { fg = colorPalette.cyan },
  htmlTagName = { fg = colorPalette.cyan },
  htmlTitle = { fg = colorPalette.white },

  -- Markdown
  markdownBlockquote = { fg = colorPalette.yellow, italic = true },
  markdownBold = { fg = colorPalette.orange, bold = true },
  markdownCode = { fg = colorPalette.green },
  markdownCodeBlock = { fg = colorPalette.orange },
  markdownCodeDelimiter = { fg = colorPalette.red },
  markdownH2 = { link = "rainbow2" },
  markdownH1 = { link = "rainbow1" },
  markdownH3 = { link = "rainbow3" },
  markdownH4 = { link = "rainbow4" },
  markdownH5 = { link = "rainbow5" },
  markdownH6 = { link = "rainbow6" },
  markdownHeadingDelimiter = { fg = colorPalette.red },
  markdownHeadingRule = { fg = colorPalette.comment },
  markdownId = { fg = colorPalette.purple },
  markdownIdDeclaration = { fg = colorPalette.cyan },
  markdownIdDelimiter = { fg = colorPalette.purple },
  markdownItalic = { fg = colorPalette.yellow, italic = true },
  markdownLinkDelimiter = { fg = colorPalette.purple },
  markdownLinkText = { fg = colorPalette.pink },
  markdownListMarker = { fg = colorPalette.cyan },
  markdownOrderedListMarker = { fg = colorPalette.red },
  markdownRule = { fg = colorPalette.comment },
  ["@markup.heading.1.markdown"] = { link = "rainbowcol1" },
  ["@markup.heading.2.markdown"] = { link = "rainbowcol2" },
  ["@markup.heading.3.markdown"] = { link = "rainbowcol3" },
  ["@markup.heading.4.markdown"] = { link = "rainbowcol4" },
  ["@markup.heading.5.markdown"] = { link = "rainbowcol5" },
  ["@markup.heading.6.markdown"] = { link = "rainbowcol6" },

  --  Diff
  diffAdded = { fg = colorPalette.green },
  diffRemoved = { fg = colorPalette.red },
  diffFileId = { fg = colorPalette.yellow, bold = true, reverse = true },
  diffFile = { fg = colorPalette.nontext },
  diffNewFile = { fg = colorPalette.green },
  diffOldFile = { fg = colorPalette.red },

  debugPc = { bg = colorPalette.menu },
  debugBreakpoint = { fg = colorPalette.red, reverse = true },

  -- Telescope
  TelescopePromptBorder = { fg = colorPalette.comment },
  TelescopeResultsBorder = { fg = colorPalette.comment },
  TelescopePreviewBorder = { fg = colorPalette.comment },
  TelescopeSelection = { fg = colorPalette.white, bg = colorPalette.selection },
  TelescopeMultiSelection = { fg = colorPalette.purple, bg = colorPalette.selection },
  TelescopeNormal = { fg = colorPalette.foreground, bg = colorPalette.background },
  TelescopeMatching = { fg = colorPalette.green },
  TelescopePromptPrefix = { fg = colorPalette.purple },
  TelescopeResultsDiffDelete = { fg = colorPalette.red },
  TelescopeResultsDiffChange = { fg = colorPalette.cyan },
  TelescopeResultsDiffAdd = { fg = colorPalette.green },

  -- LSP
  DiagnosticError = { fg = colorPalette.red },
  DiagnosticWarn = { fg = colorPalette.yellow },
  DiagnosticInfo = { fg = colorPalette.cyan },
  DiagnosticHint = { fg = colorPalette.cyan },
  DiagnosticUnderlineError = { undercurl = true, sp = colorPalette.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = colorPalette.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = colorPalette.cyan },
  DiagnosticUnderlineHint = { undercurl = true, sp = colorPalette.cyan },
  DiagnosticSignError = { fg = colorPalette.red },
  DiagnosticSignWarn = { fg = colorPalette.yellow },
  DiagnosticSignInfo = { fg = colorPalette.cyan },
  DiagnosticSignHint = { fg = colorPalette.cyan },
  DiagnosticFloatingError = { fg = colorPalette.red },
  DiagnosticFloatingWarn = { fg = colorPalette.yellow },
  DiagnosticFloatingInfo = { fg = colorPalette.cyan },
  DiagnosticFloatingHint = { fg = colorPalette.cyan },
  DiagnosticVirtualTextError = { fg = colorPalette.red },
  DiagnosticVirtualTextWarn = { fg = colorPalette.yellow },
  DiagnosticVirtualTextInfo = { fg = colorPalette.cyan },
  DiagnosticVirtualTextHint = { fg = colorPalette.cyan },

  LspDiagnosticsDefaultError = { fg = colorPalette.red },
  LspDiagnosticsDefaultWarning = { fg = colorPalette.yellow },
  LspDiagnosticsDefaultInformation = { fg = colorPalette.cyan },
  LspDiagnosticsDefaultHint = { fg = colorPalette.cyan },
  LspDiagnosticsUnderlineError = { fg = colorPalette.red, undercurl = true },
  LspDiagnosticsUnderlineWarning = { fg = colorPalette.yellow, undercurl = true },
  LspDiagnosticsUnderlineInformation = { fg = colorPalette.cyan, undercurl = true },
  LspDiagnosticsUnderlineHint = { fg = colorPalette.cyan, undercurl = true },
  LspReferenceText = { fg = colorPalette.orange },
  LspReferenceRead = { fg = colorPalette.orange },
  LspReferenceWrite = { fg = colorPalette.orange },
  LspCodeLens = { fg = colorPalette.cyan },
  LspInlayHint = { fg = colorPalette.gray, bg = colorPalette.backgroundLight },
}

return {
  colors = colorPalette,
  groups = GROUPS,
}
