local COLOR_PALETTE = {
  bg = "#282A36",
  fg = "#F8F8F2",
  selection = "#44475A",
  comment = "#6272A4",
  red = "#FF5555",
  orange = "#FFB86C",
  yellow = "#F1FA8C",
  green = "#50fa7b",
  purple = "#BD93F9",
  cyan = "#8BE9FD",
  pink = "#FF79C6",
  bright_red = "#FF6E6E",
  bright_green = "#69FF94",
  bright_yellow = "#FFFFA5",
  bright_blue = "#D6ACFF",
  bright_magenta = "#FF92DF",
  bright_cyan = "#A4FFFF",
  bright_white = "#FFFFFF",
  menu = "#21222C",
  visual = "#3E4452",
  gutter_fg = "#4B5263",
  nontext = "#3B4048",
  white = "#ABB2BF",
  black = "#191A21",
}

local GROUPS = {
  Normal = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.bg },
  NormalFloat = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.bg },
  Comment = { fg = COLOR_PALETTE.comment, italic = true },
  Constant = { fg = COLOR_PALETTE.yellow },
  String = { fg = COLOR_PALETTE.yellow },
  Character = { fg = COLOR_PALETTE.green },
  Number = { fg = COLOR_PALETTE.orange },
  Boolean = { fg = COLOR_PALETTE.cyan },
  Float = { fg = COLOR_PALETTE.orange },
  FloatBorder = { fg = COLOR_PALETTE.white },
  Operator = { fg = COLOR_PALETTE.purple },
  Keyword = { fg = COLOR_PALETTE.cyan },
  Keywords = { fg = COLOR_PALETTE.cyan },
  Identifier = { fg = COLOR_PALETTE.cyan },
  Function = { fg = COLOR_PALETTE.yellow },
  Statement = { fg = COLOR_PALETTE.purple },
  Conditional = { fg = COLOR_PALETTE.pink },
  Repeat = { fg = COLOR_PALETTE.pink },
  Label = { fg = COLOR_PALETTE.cyan },
  Exception = { fg = COLOR_PALETTE.purple },
  PreProc = { fg = COLOR_PALETTE.yellow },
  Include = { fg = COLOR_PALETTE.purple },
  Define = { fg = COLOR_PALETTE.purple },
  Title = { fg = COLOR_PALETTE.cyan },
  Macro = { fg = COLOR_PALETTE.purple },
  PreCondit = { fg = COLOR_PALETTE.cyan },
  Type = { fg = COLOR_PALETTE.cyan },
  StorageClass = { fg = COLOR_PALETTE.pink },
  Structure = { fg = COLOR_PALETTE.yellow },
  TypeDef = { fg = COLOR_PALETTE.yellow },
  Special = { fg = COLOR_PALETTE.green, italic = true },
  SpecialComment = { fg = COLOR_PALETTE.comment, italic = true },
  Error = { fg = COLOR_PALETTE.bright_red },
  Todo = { fg = COLOR_PALETTE.purple, bold = true, italic = true },
  Underlined = { fg = COLOR_PALETTE.cyan, underline = true },

  Cursor = { reverse = true },
  CursorLineNr = { fg = COLOR_PALETTE.fg, bold = true },

  SignColumn = { bg = COLOR_PALETTE.bg },

  Conceal = { fg = COLOR_PALETTE.comment },
  CursorColumn = { bg = COLOR_PALETTE.black },
  CursorLine = { bg = COLOR_PALETTE.selection },
  ColorColumn = { bg = COLOR_PALETTE.selection },

  StatusLine = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.selection },
  StatusLineNC = { fg = COLOR_PALETTE.comment },
  StatusLineTerm = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.black },
  StatusLineTermNC = { fg = COLOR_PALETTE.comment },

  Directory = { fg = COLOR_PALETTE.cyan },
  DiffAdd = { fg = COLOR_PALETTE.bg, bg = COLOR_PALETTE.green },
  DiffChange = { fg = COLOR_PALETTE.orange },
  DiffDelete = { fg = COLOR_PALETTE.red },
  DiffText = { fg = COLOR_PALETTE.comment },

  ErrorMsg = { fg = COLOR_PALETTE.bright_red },
  VertSplit = { fg = COLOR_PALETTE.black },
  WinSeparator = { fg = COLOR_PALETTE.black },
  Folded = { fg = COLOR_PALETTE.comment },
  FoldColumn = {},
  Search = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.orange },
  IncSearch = { fg = COLOR_PALETTE.orange, bg = COLOR_PALETTE.comment },
  LineNr = { fg = COLOR_PALETTE.comment },
  MatchParen = { fg = COLOR_PALETTE.fg, underline = true },
  NonText = { fg = COLOR_PALETTE.nontext },
  Pmenu = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.menu },
  PmenuSel = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.selection },
  PmenuSbar = { bg = COLOR_PALETTE.bg },
  PmenuThumb = { bg = COLOR_PALETTE.selection },

  Question = { fg = COLOR_PALETTE.purple },
  QuickFixLine = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.yellow },
  SpecialKey = { fg = COLOR_PALETTE.nontext },

  SpellBad = { fg = COLOR_PALETTE.bright_red, underline = true },
  SpellCap = { fg = COLOR_PALETTE.yellow },
  SpellLocal = { fg = COLOR_PALETTE.yellow },
  SpellRare = { fg = COLOR_PALETTE.yellow },

  TabLine = { fg = COLOR_PALETTE.comment },
  TabLineSel = { fg = COLOR_PALETTE.white },
  TabLineFill = { bg = COLOR_PALETTE.bg },
  Terminal = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.black },
  Visual = { bg = COLOR_PALETTE.visual },
  VisualNOS = { fg = COLOR_PALETTE.visual },
  WarningMsg = { fg = COLOR_PALETTE.yellow },
  WildMenu = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.white },

  EndOfBuffer = { fg = COLOR_PALETTE.bg },

  -- TreeSitter
  ["@error"] = { fg = COLOR_PALETTE.bright_red },
  ["@punctuation.delimiter"] = { fg = COLOR_PALETTE.fg },
  ["@punctuation.bracket"] = { fg = COLOR_PALETTE.fg },
  ["@markup.list"] = { fg = COLOR_PALETTE.cyan },

  ["@constant"] = { fg = COLOR_PALETTE.purple },
  ["@constant.builtin"] = { fg = COLOR_PALETTE.purple },
  ["@markup.link.label.symbol"] = { fg = COLOR_PALETTE.purple },

  ["@constant.macro"] = { fg = COLOR_PALETTE.cyan },
  ["@string.regexp"] = { fg = COLOR_PALETTE.red },
  ["@string"] = { fg = COLOR_PALETTE.yellow },
  ["@string.escape"] = { fg = COLOR_PALETTE.cyan },
  ["@string.special.symbol"] = { fg = COLOR_PALETTE.purple },
  ["@character"] = { fg = COLOR_PALETTE.green },
  ["@number"] = { fg = COLOR_PALETTE.purple },
  ["@boolean"] = { fg = COLOR_PALETTE.purple },
  ["@number.float"] = { fg = COLOR_PALETTE.green },
  ["@annotation"] = { fg = COLOR_PALETTE.yellow },
  ["@attribute"] = { fg = COLOR_PALETTE.cyan },
  ["@module"] = { fg = COLOR_PALETTE.orange },

  ["@function.builtin"] = { fg = COLOR_PALETTE.cyan },
  ["@function"] = { fg = COLOR_PALETTE.green },
  ["@function.macro"] = { fg = COLOR_PALETTE.green },
  ["@variable.parameter"] = { fg = COLOR_PALETTE.orange },
  ["@variable.parameter.reference"] = { fg = COLOR_PALETTE.orange },
  ["@function.method"] = { fg = COLOR_PALETTE.green },
  ["@variable.member"] = { fg = COLOR_PALETTE.orange },
  ["@property"] = { fg = COLOR_PALETTE.purple },
  ["@constructor"] = { fg = COLOR_PALETTE.cyan },

  ["@keyword.conditional"] = { fg = COLOR_PALETTE.pink },
  ["@keyword.repeat"] = { fg = COLOR_PALETTE.pink },
  ["@label"] = { fg = COLOR_PALETTE.cyan },

  ["@keyword"] = { fg = COLOR_PALETTE.pink },
  ["@keyword.function"] = { fg = COLOR_PALETTE.cyan },
  ["@keyword.function.ruby"] = { fg = COLOR_PALETTE.pink },
  ["@keyword.operator"] = { fg = COLOR_PALETTE.pink },
  ["@operator"] = { fg = COLOR_PALETTE.pink },
  ["@keyword.exception"] = { fg = COLOR_PALETTE.purple },
  ["@type"] = { fg = COLOR_PALETTE.bright_cyan },
  ["@type.builtin"] = { fg = COLOR_PALETTE.cyan, italic = true },
  ["@type.qualifier"] = { fg = COLOR_PALETTE.pink },
  ["@structure"] = { fg = COLOR_PALETTE.purple },
  ["@keyword.include"] = { fg = COLOR_PALETTE.pink },

  ["@variable"] = { fg = COLOR_PALETTE.fg },
  ["@variable.builtin"] = { fg = COLOR_PALETTE.purple },

  ["@markup"] = { fg = COLOR_PALETTE.orange },
  ["@markup.strong"] = { fg = COLOR_PALETTE.orange, bold = true }, -- bold
  ["@markup.emphasis"] = { fg = COLOR_PALETTE.yellow, italic = true }, -- italic
  ["@markup.underline"] = { fg = COLOR_PALETTE.orange },
  ["@markup.heading"] = { fg = COLOR_PALETTE.pink, bold = true }, -- title
  ["@markup.raw"] = { fg = COLOR_PALETTE.yellow }, -- inline code
  ["@markup.link.url"] = { fg = COLOR_PALETTE.yellow, italic = true }, -- urls
  ["@markup.link"] = { fg = COLOR_PALETTE.orange, bold = true },

  ["@tag"] = { fg = COLOR_PALETTE.cyan },
  ["@tag.attribute"] = { fg = COLOR_PALETTE.green },
  ["@tag.delimiter"] = { fg = COLOR_PALETTE.cyan },

  -- Semantic
  ["@class"] = { fg = COLOR_PALETTE.cyan },
  ["@struct"] = { fg = COLOR_PALETTE.cyan },
  ["@enum"] = { fg = COLOR_PALETTE.cyan },
  ["@enumMember"] = { fg = COLOR_PALETTE.purple },
  ["@event"] = { fg = COLOR_PALETTE.cyan },
  ["@interface"] = { fg = COLOR_PALETTE.cyan },
  ["@modifier"] = { fg = COLOR_PALETTE.cyan },
  ["@regexp"] = { fg = COLOR_PALETTE.yellow },
  ["@typeParameter"] = { fg = COLOR_PALETTE.cyan },
  ["@decorator"] = { fg = COLOR_PALETTE.cyan },

  -- LSP Semantic (0.9+)
  ["@lsp.type.class"] = { fg = COLOR_PALETTE.cyan },
  ["@lsp.type.enum"] = { fg = COLOR_PALETTE.cyan },
  ["@lsp.type.decorator"] = { fg = COLOR_PALETTE.green },
  ["@lsp.type.enumMember"] = { fg = COLOR_PALETTE.purple },
  ["@lsp.type.function"] = { fg = COLOR_PALETTE.green },
  ["@lsp.type.interface"] = { fg = COLOR_PALETTE.cyan },
  ["@lsp.type.macro"] = { fg = COLOR_PALETTE.cyan },
  ["@lsp.type.method"] = { fg = COLOR_PALETTE.green },
  ["@lsp.type.namespace"] = { fg = COLOR_PALETTE.orange },
  ["@lsp.type.parameter"] = { fg = COLOR_PALETTE.orange },
  ["@lsp.type.property"] = { fg = COLOR_PALETTE.purple },
  ["@lsp.type.struct"] = { fg = COLOR_PALETTE.cyan },
  ["@lsp.type.type"] = { fg = COLOR_PALETTE.bright_cyan },
  ["@lsp.type.variable"] = { fg = COLOR_PALETTE.fg },

  -- HTML
  htmlArg = { fg = COLOR_PALETTE.green },
  htmlBold = { fg = COLOR_PALETTE.yellow, bold = true },
  htmlEndTag = { fg = COLOR_PALETTE.cyan },
  htmlH1 = { fg = COLOR_PALETTE.pink },
  htmlH2 = { fg = COLOR_PALETTE.pink },
  htmlH3 = { fg = COLOR_PALETTE.pink },
  htmlH4 = { fg = COLOR_PALETTE.pink },
  htmlH5 = { fg = COLOR_PALETTE.pink },
  htmlH6 = { fg = COLOR_PALETTE.pink },
  htmlItalic = { fg = COLOR_PALETTE.purple, italic = true },
  htmlLink = { fg = COLOR_PALETTE.purple, underline = true },
  htmlSpecialChar = { fg = COLOR_PALETTE.yellow },
  htmlSpecialTagName = { fg = COLOR_PALETTE.cyan },
  htmlTag = { fg = COLOR_PALETTE.cyan },
  htmlTagN = { fg = COLOR_PALETTE.cyan },
  htmlTagName = { fg = COLOR_PALETTE.cyan },
  htmlTitle = { fg = COLOR_PALETTE.white },

  -- Markdown
  markdownBlockquote = { fg = COLOR_PALETTE.yellow, italic = true },
  markdownBold = { fg = COLOR_PALETTE.orange, bold = true },
  markdownCode = { fg = COLOR_PALETTE.green },
  markdownCodeBlock = { fg = COLOR_PALETTE.orange },
  markdownCodeDelimiter = { fg = COLOR_PALETTE.red },
  markdownH2 = { link = "rainbow2" },
  markdownH1 = { link = "rainbow1" },
  markdownH3 = { link = "rainbow3" },
  markdownH4 = { link = "rainbow4" },
  markdownH5 = { link = "rainbow5" },
  markdownH6 = { link = "rainbow6" },
  markdownHeadingDelimiter = { fg = COLOR_PALETTE.red },
  markdownHeadingRule = { fg = COLOR_PALETTE.comment },
  markdownId = { fg = COLOR_PALETTE.purple },
  markdownIdDeclaration = { fg = COLOR_PALETTE.cyan },
  markdownIdDelimiter = { fg = COLOR_PALETTE.purple },
  markdownItalic = { fg = COLOR_PALETTE.yellow, italic = true },
  markdownLinkDelimiter = { fg = COLOR_PALETTE.purple },
  markdownLinkText = { fg = COLOR_PALETTE.pink },
  markdownListMarker = { fg = COLOR_PALETTE.cyan },
  markdownOrderedListMarker = { fg = COLOR_PALETTE.red },
  markdownRule = { fg = COLOR_PALETTE.comment },
  ["@markup.heading.1.markdown"] = { link = "rainbowcol1" },
  ["@markup.heading.2.markdown"] = { link = "rainbowcol2" },
  ["@markup.heading.3.markdown"] = { link = "rainbowcol3" },
  ["@markup.heading.4.markdown"] = { link = "rainbowcol4" },
  ["@markup.heading.5.markdown"] = { link = "rainbowcol5" },
  ["@markup.heading.6.markdown"] = { link = "rainbowcol6" },

  --  Diff
  diffAdded = { fg = COLOR_PALETTE.green },
  diffRemoved = { fg = COLOR_PALETTE.red },
  diffFileId = { fg = COLOR_PALETTE.yellow, bold = true, reverse = true },
  diffFile = { fg = COLOR_PALETTE.nontext },
  diffNewFile = { fg = COLOR_PALETTE.green },
  diffOldFile = { fg = COLOR_PALETTE.red },

  debugPc = { bg = COLOR_PALETTE.menu },
  debugBreakpoint = { fg = COLOR_PALETTE.red, reverse = true },

  -- Git Signs
  GitSignsAdd = { fg = COLOR_PALETTE.bright_green },
  GitSignsChange = { fg = COLOR_PALETTE.cyan },
  GitSignsDelete = { fg = COLOR_PALETTE.bright_red },
  GitSignsAddLn = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.bright_green },
  GitSignsChangeLn = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.cyan },
  GitSignsDeleteLn = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.bright_red },
  GitSignsCurrentLineBlame = { fg = COLOR_PALETTE.white },

  -- Telescope
  TelescopePromptBorder = { fg = COLOR_PALETTE.comment },
  TelescopeResultsBorder = { fg = COLOR_PALETTE.comment },
  TelescopePreviewBorder = { fg = COLOR_PALETTE.comment },
  TelescopeSelection = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.selection },
  TelescopeMultiSelection = { fg = COLOR_PALETTE.purple, bg = COLOR_PALETTE.selection },
  TelescopeNormal = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.bg },
  TelescopeMatching = { fg = COLOR_PALETTE.green },
  TelescopePromptPrefix = { fg = COLOR_PALETTE.purple },
  TelescopeResultsDiffDelete = { fg = COLOR_PALETTE.red },
  TelescopeResultsDiffChange = { fg = COLOR_PALETTE.cyan },
  TelescopeResultsDiffAdd = { fg = COLOR_PALETTE.green },

  -- Flash
  FlashLabel = { bg = COLOR_PALETTE.red, fg = COLOR_PALETTE.bright_white },

  -- NvimTree
  NvimTreeNormal = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.menu },
  NvimTreeVertSplit = { fg = COLOR_PALETTE.bg, bg = COLOR_PALETTE.bg },
  NvimTreeRootFolder = { fg = COLOR_PALETTE.fg, bold = true },
  NvimTreeGitDirty = { fg = COLOR_PALETTE.yellow },
  NvimTreeGitNew = { fg = COLOR_PALETTE.bright_green },
  NvimTreeImageFile = { fg = COLOR_PALETTE.pink },
  NvimTreeFolderIcon = { fg = COLOR_PALETTE.purple },
  NvimTreeIndentMarker = { fg = COLOR_PALETTE.nontext },
  NvimTreeEmptyFolderName = { fg = COLOR_PALETTE.comment },
  NvimTreeFolderName = { fg = COLOR_PALETTE.fg },
  NvimTreeSpecialFile = { fg = COLOR_PALETTE.pink, underline = true },
  NvimTreeOpenedFolderName = { fg = COLOR_PALETTE.fg },
  NvimTreeCursorLine = { bg = COLOR_PALETTE.selection },
  NvimTreeIn = { bg = COLOR_PALETTE.selection },

  NvimTreeEndOfBuffer = { fg = COLOR_PALETTE.bg },

  -- NeoTree
  NeoTreeNormal = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.menu },
  NeoTreeNormalNC = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.menu },
  NeoTreeDirectoryName = { fg = COLOR_PALETTE.fg },
  NeoTreeGitUnstaged = { fg = COLOR_PALETTE.bright_magenta },
  NeoTreeGitModified = { fg = COLOR_PALETTE.bright_magenta },
  NeoTreeGitUntracked = { fg = COLOR_PALETTE.bright_green },
  NeoTreeDirectoryIcon = { fg = COLOR_PALETTE.purple },
  NeoTreeIndentMarker = { fg = COLOR_PALETTE.nontext },
  NeoTreeDotfile = { fg = COLOR_PALETTE.comment },

  -- Bufferline
  BufferLineIndicatorSelected = { fg = COLOR_PALETTE.purple },
  BufferLineFill = { bg = COLOR_PALETTE.black },
  BufferLineBufferSelected = { bg = COLOR_PALETTE.bg },
  BufferLineSeparator = { fg = COLOR_PALETTE.black },

  -- LSP
  DiagnosticError = { fg = COLOR_PALETTE.red },
  DiagnosticWarn = { fg = COLOR_PALETTE.yellow },
  DiagnosticInfo = { fg = COLOR_PALETTE.cyan },
  DiagnosticHint = { fg = COLOR_PALETTE.cyan },
  DiagnosticUnderlineError = { undercurl = true, sp = COLOR_PALETTE.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = COLOR_PALETTE.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = COLOR_PALETTE.cyan },
  DiagnosticUnderlineHint = { undercurl = true, sp = COLOR_PALETTE.cyan },
  DiagnosticSignError = { fg = COLOR_PALETTE.red },
  DiagnosticSignWarn = { fg = COLOR_PALETTE.yellow },
  DiagnosticSignInfo = { fg = COLOR_PALETTE.cyan },
  DiagnosticSignHint = { fg = COLOR_PALETTE.cyan },
  DiagnosticFloatingError = { fg = COLOR_PALETTE.red },
  DiagnosticFloatingWarn = { fg = COLOR_PALETTE.yellow },
  DiagnosticFloatingInfo = { fg = COLOR_PALETTE.cyan },
  DiagnosticFloatingHint = { fg = COLOR_PALETTE.cyan },
  DiagnosticVirtualTextError = { fg = COLOR_PALETTE.red },
  DiagnosticVirtualTextWarn = { fg = COLOR_PALETTE.yellow },
  DiagnosticVirtualTextInfo = { fg = COLOR_PALETTE.cyan },
  DiagnosticVirtualTextHint = { fg = COLOR_PALETTE.cyan },

  LspDiagnosticsDefaultError = { fg = COLOR_PALETTE.red },
  LspDiagnosticsDefaultWarning = { fg = COLOR_PALETTE.yellow },
  LspDiagnosticsDefaultInformation = { fg = COLOR_PALETTE.cyan },
  LspDiagnosticsDefaultHint = { fg = COLOR_PALETTE.cyan },
  LspDiagnosticsUnderlineError = { fg = COLOR_PALETTE.red, undercurl = true },
  LspDiagnosticsUnderlineWarning = { fg = COLOR_PALETTE.yellow, undercurl = true },
  LspDiagnosticsUnderlineInformation = { fg = COLOR_PALETTE.cyan, undercurl = true },
  LspDiagnosticsUnderlineHint = { fg = COLOR_PALETTE.cyan, undercurl = true },
  LspReferenceText = { fg = COLOR_PALETTE.orange },
  LspReferenceRead = { fg = COLOR_PALETTE.orange },
  LspReferenceWrite = { fg = COLOR_PALETTE.orange },
  LspCodeLens = { fg = COLOR_PALETTE.cyan },
  LspInlayHint = { fg = "#969696", bg = "#2f3146" },

  --LSP Saga
  LspFloatWinNormal = { fg = COLOR_PALETTE.fg },
  LspFloatWinBorder = { fg = COLOR_PALETTE.comment },
  LspSagaHoverBorder = { fg = COLOR_PALETTE.comment },
  LspSagaSignatureHelpBorder = { fg = COLOR_PALETTE.comment },
  LspSagaCodeActionBorder = { fg = COLOR_PALETTE.comment },
  LspSagaDefPreviewBorder = { fg = COLOR_PALETTE.comment },
  LspLinesDiagBorder = { fg = COLOR_PALETTE.comment },
  LspSagaRenameBorder = { fg = COLOR_PALETTE.comment },
  LspSagaBorderTitle = { fg = COLOR_PALETTE.menu },
  LSPSagaDiagnosticTruncateLine = { fg = COLOR_PALETTE.comment },
  LspSagaDiagnosticBorder = { fg = COLOR_PALETTE.comment },
  LspSagaShTruncateLine = { fg = COLOR_PALETTE.comment },
  LspSagaDocTruncateLine = { fg = COLOR_PALETTE.comment },
  LspSagaLspFinderBorder = { fg = COLOR_PALETTE.comment },
  CodeActionNumber = { bg = "NONE", fg = COLOR_PALETTE.cyan },

  -- IndentBlankLine
  IndentBlanklineContextChar = { fg = COLOR_PALETTE.bright_red, nocombine = true },

  -- Nvim compe
  CmpItemAbbrDeprecated = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.bg },
  CmpItemAbbrMatch = { fg = COLOR_PALETTE.cyan, bg = COLOR_PALETTE.bg },

  -- barbar
  BufferVisibleTarget = { fg = COLOR_PALETTE.red },
  BufferTabpages = { fg = COLOR_PALETTE.nontext, bg = COLOR_PALETTE.black, bold = true },
  BufferTabpageFill = { fg = COLOR_PALETTE.nontext, bg = COLOR_PALETTE.black },
  BufferCurrentSign = { fg = COLOR_PALETTE.purple },
  BufferCurrentTarget = { fg = COLOR_PALETTE.red },
  BufferInactive = { fg = COLOR_PALETTE.comment, bg = COLOR_PALETTE.black, italic = true },
  BufferInactiveIndex = { fg = COLOR_PALETTE.nontext, bg = COLOR_PALETTE.black, italic = true },
  BufferInactiveMod = { fg = COLOR_PALETTE.yellow, bg = COLOR_PALETTE.black, italic = true },
  BufferInactiveSign = { fg = COLOR_PALETTE.nontext, bg = COLOR_PALETTE.black, italic = true },
  BufferInactiveTarget = { fg = COLOR_PALETTE.red, bg = COLOR_PALETTE.black, bold = true },

  -- Compe
  CompeDocumentation = { link = "Pmenu" },
  CompeDocumentationBorder = { link = "Pmenu" },

  -- Cmp
  CmpItemAbbr = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.bg },
  CmpItemKind = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.bg },
  CmpItemKindMethod = { link = "@function.method" },
  CmpItemKindText = { link = "@markup" },
  CmpItemKindFunction = { link = "@function" },
  CmpItemKindConstructor = { link = "@type" },
  CmpItemKindVariable = { link = "@variable" },
  CmpItemKindClass = { link = "@type" },
  CmpItemKindInterface = { link = "@type" },
  CmpItemKindModule = { link = "@module" },
  CmpItemKindProperty = { link = "@property" },
  CmpItemKindOperator = { link = "@operator" },
  CmpItemKindReference = { link = "@variable.parameter.reference" },
  CmpItemKindUnit = { link = "@variable.member" },
  CmpItemKindValue = { link = "@variable.member" },
  CmpItemKindField = { link = "@variable.member" },
  CmpItemKindEnum = { link = "@variable.member" },
  CmpItemKindKeyword = { link = "@keyword" },
  CmpItemKindSnippet = { link = "@markup" },
  CmpItemKindColor = { link = "DevIconCss" },
  CmpItemKindFile = { link = "TSURI" },
  CmpItemKindFolder = { link = "TSURI" },
  CmpItemKindEvent = { link = "@constant" },
  CmpItemKindEnumMember = { link = "@variable.member" },
  CmpItemKindConstant = { link = "@constant" },
  CmpItemKindStruct = { link = "@structure" },
  CmpItemKindTypeParameter = { link = "@variable.parameter" },

  -- Blink
  BlinkCmpLabel = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.menu },
  BlinkCmpLabelDeprecated = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.menu },
  BlinkCmpLabelMatch = { fg = COLOR_PALETTE.cyan, bg = COLOR_PALETTE.menu },
  BlinkCmpKind = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.menu },
  BlinkCmpScrollBarThumb = { bg = COLOR_PALETTE.fg },
  BlinkCmpScrollBarGutter = { bg = COLOR_PALETTE.menu },
  BlinkCmpKindFunction = { link = "@function" },
  BlinkCmpKindConstructor = { link = "@type" },
  BlinkCmpKindVariable = { link = "@variable" },
  BlinkCmpKindClass = { link = "@type" },
  BlinkCmpKindInterface = { link = "@type" },
  BlinkCmpKindModule = { link = "@module" },
  BlinkCmpKindProperty = { link = "@property" },
  BlinkCmpKindOperator = { link = "@operator" },
  BlinkCmpKindReference = { link = "@variable.parameter.reference" },
  BlinkCmpKindUnit = { link = "@variable.member" },
  BlinkCmpKindValue = { link = "@variable.member" },
  BlinkCmpKindField = { link = "@variable.member" },
  BlinkCmpKindEnum = { link = "@variable.member" },
  BlinkCmpKindKeyword = { link = "@keyword" },
  BlinkCmpKindSnippet = { link = "@markup" },
  BlinkCmpKindColor = { link = "DevIconCss" },
  BlinkCmpKindFile = { link = "TSURI" },
  BlinkCmpKindFolder = { link = "TSURI" },
  BlinkCmpKindEvent = { link = "@constant" },
  BlinkCmpKindEnumMember = { link = "@variable.member" },
  BlinkCmpKindConstant = { link = "@constant" },
  BlinkCmpKindStruct = { link = "@structure" },
  BlinkCmpKindTypeParameter = { link = "@variable.parameter" },

  -- navic
  NavicIconsFile = { link = "CmpItemKindFile" },
  NavicIconsModule = { link = "CmpItemKindModule" },
  NavicIconsNamespace = { link = "CmpItemKindModule" },
  NavicIconsPackage = { link = "CmpItemKindModule" },
  NavicIconsClass = { link = "CmpItemKindClass" },
  NavicIconsMethod = { link = "CmpItemKindMethod" },
  NavicIconsProperty = { link = "CmpItemKindProperty" },
  NavicIconsField = { link = "CmpItemKindField" },
  NavicIconsConstructor = { link = "CmpItemKindConstructor" },
  NavicIconsEnum = { link = "CmpItemKindEnum" },
  NavicIconsInterface = { link = "CmpItemKindInterface" },
  NavicIconsFunction = { link = "CmpItemKindFunction" },
  NavicIconsVariable = { link = "CmpItemKindVariable" },
  NavicIconsConstant = { link = "CmpItemKindConstant" },
  NavicIconsString = { link = "String" },
  NavicIconsNumber = { link = "Number" },
  NavicIconsBoolean = { link = "Boolean" },
  NavicIconsArray = { link = "CmpItemKindClass" },
  NavicIconsObject = { link = "CmpItemKindClass" },
  NavicIconsKey = { link = "CmpItemKindKeyword" },
  NavicIconsKeyword = { link = "CmpItemKindKeyword" },
  NavicIconsNull = { fg = "blue" },
  NavicIconsEnumMember = { link = "CmpItemKindEnumMember" },
  NavicIconsStruct = { link = "CmpItemKindStruct" },
  NavicIconsEvent = { link = "CmpItemKindEvent" },
  NavicIconsOperator = { link = "CmpItemKindOperator" },
  NavicIconsTypeParameter = { link = "CmpItemKindTypeParameter" },
  NavicText = { fg = "gray" },
  NavicSeparator = { fg = "gray" },

  -- TS rainbow colors
  rainbowcol1 = { fg = COLOR_PALETTE.fg },
  rainbowcol2 = { fg = COLOR_PALETTE.pink },
  rainbowcol3 = { fg = COLOR_PALETTE.cyan },
  rainbowcol4 = { fg = COLOR_PALETTE.green },
  rainbowcol5 = { fg = COLOR_PALETTE.purple },
  rainbowcol6 = { fg = COLOR_PALETTE.orange },
  rainbowcol7 = { fg = COLOR_PALETTE.fg },

  -- Rainbow delimiter
  RainbowDelimiterRed = { fg = COLOR_PALETTE.fg },
  RainbowDelimiterYellow = { fg = COLOR_PALETTE.pink },
  RainbowDelimiterBlue = { fg = COLOR_PALETTE.cyan },
  RainbowDelimiterOrange = { fg = COLOR_PALETTE.green },
  RainbowDelimiterGreen = { fg = COLOR_PALETTE.purple },
  RainbowDelimiterViolet = { fg = COLOR_PALETTE.orange },
  RainbowDelimiterCyan = { fg = COLOR_PALETTE.fg },

  -- mini.indentscope
  MiniIndentscopeSymbol = { fg = "#B5629B" },
  MiniIndentscopeSymbolOff = { fg = "#B5629B" },

  -- mini.icons
  MiniIconsAzure = { fg = COLOR_PALETTE.bright_cyan },
  MiniIconsBlue = { fg = COLOR_PALETTE.bright_blue },
  MiniIconsCyan = { fg = COLOR_PALETTE.cyan },
  MiniIconsGrey = { fg = COLOR_PALETTE.white },
  MiniIconsOrange = { fg = COLOR_PALETTE.orange },
  MiniIconsPurple = { fg = COLOR_PALETTE.purple },
  MiniIconsRed = { fg = COLOR_PALETTE.red },
  MiniIconsYellow = { fg = COLOR_PALETTE.yellow },

  -- mini.statusline
  MiniStatuslineModeNormal = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.purple, bold = true },
  MiniStatuslineModeInsert = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.green, bold = true },
  MiniStatuslineModeVisual = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.pink, bold = true },
  MiniStatuslineModeReplace = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.yellow, bold = true },
  MiniStatuslineModeCommand = { fg = COLOR_PALETTE.black, bg = COLOR_PALETTE.cyan, bold = true },
  MiniStatuslineInactive = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.visual, bold = true },
  MiniStatuslineDevinfo = { fg = COLOR_PALETTE.purple, bg = COLOR_PALETTE.black },
  MiniStatuslineFilename = { fg = COLOR_PALETTE.white, bg = COLOR_PALETTE.black },
  MiniStatuslineFileinfo = { fg = COLOR_PALETTE.purple, bg = COLOR_PALETTE.black },

  -- mini.files
  MiniFilesNormal = { fg = COLOR_PALETTE.fg, bg = COLOR_PALETTE.menu },
  MiniFilesBorder = { fg = COLOR_PALETTE.purple, bg = COLOR_PALETTE.menu },
  MiniFilesBorderModified = {},
  MiniFilesCursorLine = { bg = COLOR_PALETTE.selection },
  MiniFilesDirectory = { fg = COLOR_PALETTE.fg },
  MiniFilesFile = { fg = COLOR_PALETTE.fg },
  MiniFilesTitle = { fg = COLOR_PALETTE.fg },
  MiniFilesTitleFocused = { fg = COLOR_PALETTE.yellow },

  -- goolord/alpha-nvim
  AlphaHeader = { fg = COLOR_PALETTE.purple },
  AlphaButtons = { fg = COLOR_PALETTE.cyan },
  AlphaShortcut = { fg = COLOR_PALETTE.orange },
  AlphaFooter = { fg = COLOR_PALETTE.purple, italic = true },

  -- nvimdev/dashboard-nvim
  DashboardShortCut = { fg = COLOR_PALETTE.cyan },
  DashboardHeader = { fg = COLOR_PALETTE.purple },
  DashboardCenter = { fg = COLOR_PALETTE.fg },
  DashboardFooter = { fg = COLOR_PALETTE.purple, italic = true },
  DashboardKey = { fg = COLOR_PALETTE.orange },
  DashboardDesc = { fg = COLOR_PALETTE.cyan },
  DashboardIcon = { fg = COLOR_PALETTE.cyan, bold = true },

  -- dap UI
  DapUIPlayPause = { fg = COLOR_PALETTE.bright_green },
  DapUIRestart = { fg = COLOR_PALETTE.green },
  DapUIStop = { fg = COLOR_PALETTE.red },
  DapUIStepOver = { fg = COLOR_PALETTE.cyan },
  DapUIStepInto = { fg = COLOR_PALETTE.cyan },
  DapUIStepOut = { fg = COLOR_PALETTE.cyan },
  DapUIStepBack = { fg = COLOR_PALETTE.cyan },
  DapUIType = { fg = COLOR_PALETTE.bright_blue },
  DapUIScope = { fg = COLOR_PALETTE.bright_cyan },
  DapUIModifiedValue = { fg = COLOR_PALETTE.bright_cyan, bold = true },
  DapUIDecoration = { fg = COLOR_PALETTE.bright_cyan },
  DapUIThread = { fg = COLOR_PALETTE.bright_green },
  DapUIStoppedThread = { fg = COLOR_PALETTE.bright_cyan },
  DapUISource = { fg = COLOR_PALETTE.bright_blue },
  DapUILineNumber = { fg = COLOR_PALETTE.bright_cyan },
  DapUIFloatBorder = { fg = COLOR_PALETTE.bright_cyan },
  DapUIWatchesEmpty = { fg = COLOR_PALETTE.pink },
  DapUIWatchesValue = { fg = COLOR_PALETTE.bright_green },
  DapUIWatchesError = { fg = COLOR_PALETTE.pink },
  DapUIBreakpointsPath = { fg = COLOR_PALETTE.bright_cyan },
  DapUIBreakpointsInfo = { fg = COLOR_PALETTE.bright_green },
  DapUIBreakpointsCurrentLine = { fg = COLOR_PALETTE.bright_green, bold = true },
  DapStoppedLine = { default = true, link = "Visual" },
  DapUIWinSelect = { fg = COLOR_PALETTE.bright_cyan, bold = true },

  -- Notify
  NotifyInfoIcon = { fg = COLOR_PALETTE.green },
  NotifyInfoTitle = { fg = COLOR_PALETTE.green },
  NotifyInfoBorder = { fg = "#2C453F" },
  NotifyErrorIcon = { fg = COLOR_PALETTE.red },
  NotifyErrorTitle = { fg = COLOR_PALETTE.red },
  NotifyErrorBorder = { fg = "#DD6E6B" },
  NotifyWarnIcon = { fg = COLOR_PALETTE.orange },
  NotifyWarnTitle = { fg = COLOR_PALETTE.orange },
  NotifyWarnBorder = { fg = "#785637" },

  -- SnacksDashboard
  SnacksDashboardHeader = { fg = COLOR_PALETTE.purple },
  SnacksDashboardKey = { fg = COLOR_PALETTE.orange },
  SnacksDashboardDesc = { fg = COLOR_PALETTE.cyan },
  SnacksDashboardIcon = { fg = COLOR_PALETTE.cyan },
  SnacksDashboardFooter = { fg = COLOR_PALETTE.purple, italic = true },

  -- SnacksPicker
  SnacksBackdrop = { link = "FloatShadow" },
  SnacksPickerBorder = { fg = COLOR_PALETTE.comment },
  SnacksPickerDir = { fg = COLOR_PALETTE.fg },
  SnacksPickerDirectory = { fg = COLOR_PALETTE.fg },
  SnacksPickerFile = { fg = COLOR_PALETTE.fg },
  SnacksPickerGitStatusIgnored = { fg = COLOR_PALETTE.comment },
  SnacksPickerGitStatusModified = { fg = COLOR_PALETTE.yellow },
  SnacksPickerGitStatusRenamed = { fg = COLOR_PALETTE.yellow },
  SnacksPickerGitStatusStaged = { fg = COLOR_PALETTE.bright_green },
  SnacksPickerGitStatusUnmerged = { fg = COLOR_PALETTE.orange },
  SnacksPickerGitStatusUntracked = { fg = COLOR_PALETTE.green },
  SnacksPickerInput = { link = "NormalFloat" },
  SnacksPickerInputBorder = { link = "SnacksPickerBorder" },
  SnacksPickerMatch = { fg = COLOR_PALETTE.green, italic = true },
  SnacksPickerPathHidden = { fg = COLOR_PALETTE.comment },
  SnacksPickerPrompt = { fg = COLOR_PALETTE.purple },
  SnacksPickerTitle = { fg = COLOR_PALETTE.cyan, bold = true },

  -- Neogit
  NeogitDiffAdd = { fg = COLOR_PALETTE.bright_green, bg = COLOR_PALETTE.menu },
  NeogitDiffDelete = { fg = COLOR_PALETTE.bright_red, bg = COLOR_PALETTE.menu },
  NeogitDiffContext = { fg = COLOR_PALETTE.comment, bg = COLOR_PALETTE.visual },
  NeogitDiffAddHighlight = { fg = COLOR_PALETTE.green, bg = COLOR_PALETTE.bg },
  NeogitDiffDeleteHighlight = { fg = COLOR_PALETTE.red, bg = COLOR_PALETTE.bg },
  NeogitDiffContextHighlight = { fg = COLOR_PALETTE.comment, bg = COLOR_PALETTE.visual },
  NeogitDiffAddCursor = { fg = COLOR_PALETTE.green, bg = COLOR_PALETTE.selection },
  NeogitDiffDeleteCursor = { fg = COLOR_PALETTE.red, bg = COLOR_PALETTE.selection },
  NeogitDiffContextCursor = { fg = COLOR_PALETTE.comment, bg = COLOR_PALETTE.selection },
}

return {
  colors = COLOR_PALETTE,
  groups = GROUPS,
}
