#!/usr/bin/env zsh

declare -A confLinks=(
	[config/git]="$HOME/.config/git" 
	[config/tmux]="$HOME/.config/tmux" 
	[config/nvim]="$HOME/.config/nvim"
	[config/homebrew]="$HOME/.config/homebrew"
	[config/claude]="$HOME/.config/claude"
	[config/zsh]="$HOME/.config/zsh"
	[config/ssh/config]="$HOME/.ssh/config"
	[config/zsh/zshrc]="$HOME/.zshrc"
	[scripts/dotupdate]="$HOME/.local/bin/dotupdate"
)

# Required directories that just need to exist for other actions or for the config
# to work correctly
defaultDirs=(
	"$HOME/.ssh"
	"$HOME/.config" 
	"$HOME/.cache"
	"$HOME/.config/irb" 
	"$HOME/.local/bin"
	"$HOME/.local/share/less" 
	"$HOME/.local/share/zsh"
)

echo "=== resetting env ==="
for value in "${confLinks[@]}"; do 
	echo "  🔥 $value"
	rm -rf $value; 
done
echo "✅ clean."

echo "=== creating default directories ==="
for item in "${defaultDirs[@]}"; do
	echo "  🗂️ Creating Dir: '$item'"
	mkdir -p "$item"
done
# Create gitconfig.local so that our gitconfig will not break.
touch $HOME/.gitconfig.local
echo "✅ default directories in place."

echo "=== linking config files ==="
for key value in "${(@kv)confLinks}"; do 
	echo "  🌊 Linking $HOME/workspace/dotfiles/$key => $value"
	ln -sf "$HOME/workspace/dotfiles/$key" "$value"
done
echo "✅ config files linked"

echo "=== ensuring xcode is setup ==="
xcode-select --install
echo "✅ command line tools installed"

echo "=== installing homebrew ==="
if ! command -v brew >/dev/null 2>&1; then
	sudo true
	NONINTERACTIVE=1 curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash
	/opt/homebrew/bin/brew shellenv | eval
fi
echo "✅ Homebrew installed"

echo "=== setting up GPG ==="
GPG_COUNT=$(gpg --list-keys --with-colons 2>/dev/null | grep -c '^pub:')
if [[ -z $GPG_COUNT ]]; then
	gpg --default-new-key-algo rsa4096 --gen-key
	gpg --armor --export $(gpg --list-keys --with-colons --with-fingerprint | awk -F: '/^fpr:/ { print $10 }' | tail -n 1) | pbcopy
	open "https://github.com/settings/keys"
	read -p "New gpg key is in clipboard add it to github and press enter to continue ..."
fi
echo "✅ gpg setup complete"

# Calling our linked update command
dotupdate
