#!/usr/bin/env zsh
# This script sets up the computer's ssh key, clones the repo, and calls the install script.

echo "==== generating a new ssh key"
mkdir -p ~/.ssh
ssh-keygen -t rsa -b 4096 -C "timanema@gmail.com"
eval "$(ssh-agent -s)"
ssh-add -K ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub | pbcopy
open "https://github.com/settings/keys"
read -p "New ssh key is in clipboard add it to github and press enter to continue ..."

echo "==== Cloning dotfiles"
mkdir -p ~/workspace
git clone git@github.com:tanema/dotfiles.git ~/workspace/dotfiles

echo "==== Installing"
cd ~/workspace/dotfiles && ./scripts/dotinstall
