#!/usr/bin/env bash
#MISE description="Generates claude and ghostty themes from a json file at $COLORSCHEME."
set -euo pipefail

# source the colorscheme variables as env vars to use in envsubst
$(jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' "$COLORSCHEME")
envsubst < "$DOTFILES/colorscheme/claude.tmpl" > "$DOTFILES/claude/themes/timscheme.json"
envsubst < "$DOTFILES/colorscheme/ghostty.tmpl" > "$DOTFILES/ghostty/themes/timscheme"
