#############CONFIG#################
set -g default-shell $SHELL
set -g focus-events on          # Enable focus events for each pane.
set -g allow-passthrough on     # Lets notifications and progress updates to propagate up.
set -s extended-keys on         # Let tmux distinguish multikey shortcuts.
set -as terminal-features 'xterm*:extkeys' # Ensure terminal has extkeys.
set -g history-limit 50000
set -g display-time 4000
set -g default-command "reattach-to-user-namespace -l $SHELL"
set -g default-terminal "screen-256color"
set -s default-terminal "screen-256color"
setw -g mode-keys vi            # Enable vi keys.
set -g mouse on                 # Enable mouse support.
set -g @shell_mode 'vi'
set -g status-interval 5
set -g status-keys vi
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
set -g renumber-windows on      # Renumber windows if the window closes.
# Setting index start to 1 makes sense on a keyboard
setw -g pane-base-index 1       # Set the base index for panes to 1 instead of 0.
set -g base-index 1             # Set the base index for windows to 1 instead of 0.

#############HOTKEYS################
# By remapping the `CapsLock` key to `Ctrl`,
# you can make triggering commands more comfottable!
set -g prefix C-a               # Setting the prefix from `C-b` to `C-a`.
unbind C-b                      # Free the original `Ctrl-b` prefix keybinding.
bind C-a send-keys C-a          # Send raw C-a to shell (beginning of line).
bind a send-keys C-a            # leader-a sends C-a to shell (beginning of line).
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind | split-window -h          # Splitting panes.
bind - split-window -v
bind -r C-h select-window -t :- # Moving between windows.
bind -r C-l select-window -t :+
bind -r H resize-pane -L 5      # Pane resizing.
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind h select-pane -L           # Moving between panes.
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind r source-file ~/.config/tmux/tmux.conf # Leader r reloads config

############APPEARANCE##################
set -g pane-border-style fg=purple,bg=black # Pane colors.
set -g pane-active-border-style fg=black,bg=purple,bold
set -g pane-border-status bottom
set -g pane-border-format ' #P: #{pane_current_command} '
set -g window-style fg=colour245,bg=colour234       # Dim inactive panes.
set -g window-active-style fg=default,bg=default    # Full brightness for the focused pane.
set -g message-style fg=white,bg=black,bright # Command / message line.
 # statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'
set -g status-left ''
set -g status-left-length 10
set -g status-right-style 'fg=black bg=red'
set -g status-right ''
setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '
setw -g window-status-bell-style 'fg=yellow bg=red bold'
